[project]
name = "msix-global-installer"
version = "0.1.0"
description = "Install MSIX packages globally on Windows."
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "sv-ttk>=2.6.0",
    "tk>=0.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.5",
]
